name: 'Custom Setup Python'
description: 'Устанавливает Python 3.12 на Ubuntu 24.04'
runs:
  using: "composite"
  steps:
    - name: Проверка установленного Python
      shell: bash
      run: |
        python3 --version
        which python3

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Проверка кода на PEP8
      run: |
        echo "Проверка кода на PEP8"
        flake8 app.py        