name: 'Custom Setup Python'
description: 'Устанавливает Python 3.10 на Ubuntu'
runs:
  using: "composite"
  steps:
    - name: Install Python 3.10
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10 python3.10-venv python3.10-dev
