name: 'Custom Setup Python'
description: 'Устанавливает Python 3.12 на Ubuntu 24.04'
runs:
  using: "composite"
  steps:
    - name: Проверка установленного Python
      shell: bash
      run: |
        python3 --version
        which python3
