name: 'Custom Setup Python'
description: 'Устанавливает Python 3.12 на Ubuntu 24.04'
runs:
  using: "composite"
  steps:
    - name: Проверка установленного Python
      shell: bash
      run: |
        ln -s /usr/bin/python3 /usr/bin/python || true

    - name: Установка зависимостей
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      shell: bash
      run: |
        python -m unittest discover

    - name: Проверка кода на PEP8
      shell: bash
      run: |
        echo "Проверка кода на PEP8"
        flake8 app.py        