name: 'Custom Setup Python'
description: 'Запускает тесты и проверку кода в уже готовом контейнере с Python'

runs:
  using: "composite"
  steps:
    - name: Проверка установленного Python
      shell: bash
      run: |
        python --version
        which python

    - name: Установка зависимостей (если нужно)
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск тестов
      shell: bash
      run: |
        python -m unittest discover

    - name: Проверка кода на PEP8
      shell: bash
      run: |
        echo "Проверка кода на PEP8"
        flake8 app.py
